# Generated by Django 5.2.11 on 2026-02-27 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("institutions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
            ],
            options={
                "verbose_name_plural": "News Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SDGGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.IntegerField(
                        choices=[
                            (1, "SDG 1 - No Poverty"),
                            (2, "SDG 2 - Zero Hunger"),
                            (3, "SDG 3 - Good Health and Well-being"),
                            (4, "SDG 4 - Quality Education"),
                            (5, "SDG 5 - Gender Equality"),
                            (6, "SDG 6 - Clean Water and Sanitation"),
                            (7, "SDG 7 - Affordable and Clean Energy"),
                            (8, "SDG 8 - Decent Work and Economic Growth"),
                            (9, "SDG 9 - Industry, Innovation and Infrastructure"),
                            (10, "SDG 10 - Reduced Inequalities"),
                            (11, "SDG 11 - Sustainable Cities and Communities"),
                            (12, "SDG 12 - Responsible Consumption and Production"),
                            (13, "SDG 13 - Climate Action"),
                            (14, "SDG 14 - Life Below Water"),
                            (15, "SDG 15 - Life on Land"),
                            (16, "SDG 16 - Peace, Justice and Strong Institutions"),
                            (17, "SDG 17 - Partnerships for the Goals"),
                        ],
                        unique=True,
                    ),
                ),
            ],
            options={
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="NewsItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("slug", models.SlugField(blank=True, max_length=350, unique=True)),
                (
                    "summary",
                    models.TextField(
                        help_text="Brief summary (max 500 chars)", max_length=500
                    ),
                ),
                ("content", models.TextField()),
                (
                    "video_url",
                    models.URLField(blank=True, help_text="YouTube / Vimeo URL"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending Approval"),
                            ("approved", "Approved / Published"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "featured_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="news_images/%Y/%m/"
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True, help_text="Admin feedback on approval/rejection"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="news.newscategory",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="news_items",
                        to="institutions.institution",
                    ),
                ),
                (
                    "sdg_goals",
                    models.ManyToManyField(
                        blank=True, related_name="news_items", to="news.sdggoal"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NewsImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="news_gallery/%Y/%m/")),
                ("caption", models.CharField(blank=True, max_length=200)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "news_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="news.newsitem",
                    ),
                ),
            ],
        ),
    ]
