# Generated by Django 5.2.11 on 2026-02-27 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institutions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="foundation_year",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="institution",
            name="institution_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("affiliated", "Affiliated Institute"),
                    ("autonomous", "Autonomous Institute"),
                    ("university", "University (Degree Granting)"),
                    ("technical", "Technical/Poly Techniques"),
                ],
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="institution",
            name="institution_type",
            field=models.CharField(
                blank=True,
                choices=[("college", "College"), ("university", "University")],
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="institution",
            name="place",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="institution",
            name="province",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Bengaluru", "Bengaluru"),
                    ("Chennai", "Chennai"),
                    ("Dimapur", "Dimapur"),
                    ("Guwahati", "Guwahati"),
                    ("Hyderabad", "Hyderabad"),
                    ("Kolkatta", "Kolkatta"),
                    ("Mumbai", "Mumbai"),
                    ("New Delhi", "New Delhi"),
                    ("Panjim", "Panjim"),
                    ("Shillong", "Shillong"),
                    ("Tiruchy", "Tiruchy"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="InstitutionStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_students",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Total Students"
                    ),
                ),
                (
                    "total_faculty",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Total Faculty"
                    ),
                ),
                (
                    "total_programs",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Programs Offered"
                    ),
                ),
                (
                    "total_departments",
                    models.PositiveIntegerField(default=0, verbose_name="Departments"),
                ),
                (
                    "phd_holders",
                    models.PositiveIntegerField(default=0, verbose_name="PhD Holders"),
                ),
                (
                    "research_papers",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Research Papers Published"
                    ),
                ),
                (
                    "naac_grade",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="NAAC Grade"
                    ),
                ),
                (
                    "campus_area_acres",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        verbose_name="Campus Area (acres)",
                    ),
                ),
                (
                    "placement_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Placement Rate (%)",
                    ),
                ),
                (
                    "library_books",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Library Books"
                    ),
                ),
                (
                    "hostels",
                    models.PositiveIntegerField(default=0, verbose_name="Hostels"),
                ),
                (
                    "labs",
                    models.PositiveIntegerField(default=0, verbose_name="Laboratories"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "institution",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="institutions.institution",
                    ),
                ),
            ],
            options={
                "verbose_name": "Institution Statistics",
                "verbose_name_plural": "Institution Statistics",
            },
        ),
    ]
